services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    container_name: django_app
    depends_on:
      - postgres_db
      - redis
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: celery/Dockerfile
    container_name: celery_worker
    working_dir: /app
    depends_on:
      - redis
      - app   
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  postgres_data:
