version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: ./app
    container_name: django_app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  celery:
    build: ./celery
    container_name: celery_worker
    depends_on:
      - redis
      - app
    env_file:
      - .env
    command: celery -A reservation_system worker --loglevel=info

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  postgres_data:
